### ISSUE TITLE
Bug close context menu 

### ISSUE THREAD

**Issue by StaniPetrosyan** [StaniPetrosyan/SubZero#2]
If a menu is already open, when you right-click on project or group, it should close the last menu and open a new one.

**Comment by pierrolabo** [comment]
Hello 👋 StaniPetrosyan , i have a fix for this issue ! i'll make a PR and wait for your review

**Comment by StaniPetrosyan** [comment]
Hello pierrolabo, great 😎. I am looking forward ✌️
