### ISSUE TITLE
Improve test

### ISSUE THREAD

**Issue by StaniPetrosyan** [StaniPetrosyan/SubZero#5]
Add in main.spec.test a new test using spectron that "should open group page if combination ctrl + G was clicked"

**Comment by Andrsrz** [comment]
Hi there, I can help with that. Can you assign me?

**Comment by StaniPetrosyan** [comment]
Sure 😎

**Comment by Andrsrz** [comment]
Hey @StaniPetrosyan. Just an update on this. 

I worked on the issue last saturday and I'm having a problem with the webdriverio's keys method, is not working properly so without it we can't execute keyboard shortcuts for testing. 

Right now I'm waiting for a response on an issue I opened at the spectron repo. Once that's working, the test should work and I'll open a PR with the test.

**Comment by StaniPetrosyan** [comment]
Hi @Andrsrz, no problem, we will wait. Meanwhile, you can search for bugs or add other tests if you are interested😀

**Comment by Andrsrz** [comment]
Yes! @StaniPetrosyan whenever I have a free time I'll checkout the code and see what else I can do to help.
